### ISSUE TITLE
tab spacing option

### ISSUE THREAD

**Issue by Gaiiden** [TN-1/Kode#11]
defining the tab spacing or just picking between 2 and 4 would be nice

**Comment by odiefrom** [comment]
Piggy backing on this, also being able to choose between the hard tab character and just spaces would be pretty cool.

**Comment by TN-1** [comment]
Certainly doable. Im going to start work on auto-indent soon so I will add this to the list to work on at the same time.

**Comment by Gaiiden** [comment]
Good idea, makes it easier to post on sites like pastebin where a tab makes the indent huge
auto indent yiiissssss

**Comment by TN-1** [comment]
Heres a prize for all the bug reports youve been sending me http://imgur.com/lMLaseH

**Comment by Gaiiden** [comment]
with auto indent detection for braces no less! Awesome

**Comment by TN-1** [comment]
http://imgur.com/0rlXzrA Done ;)
