### ISSUE TITLE
Unable to start if you initially do not choose a folder

### ISSUE THREAD

**Issue by fibonatic** [TN-1/Kode#12]
The first time I tried to start Kode I skipped the selection of the folder, after which the program shot down. But after I tried to run the Kode.exe again I did not got the same question to choose folders and directly shot down. Even after deleting the three files and extracting the same files from the zip file in the same folder. I had to choose a different folder where I extracted the files in order to get the folder selection menu again.

For information, I used it on windows 7.

**Comment by TN-1** [comment]
Thanks for the report. This is something I am aware of and already fixed. It will be included in the next release.
