### ISSUE TITLE
Unhandled exception when trying to open a file when all tabs are closed

### ISSUE THREAD

**Issue by fibonatic** [TN-1/Kode#13]
If I close all tabs before I try to open a file I get to following message:
![schermafdruk 2016-02-26 14 24 18](https://cloud.githubusercontent.com/assets/1704374/13353407/795dd9e2-dc94-11e5-9846-d9f22ca86975.png)
PS: I am running Kode of Windows 7

**Comment by TN-1** [comment]
This has been fixed in Issue #10  
Thanks for the report :)
