### ISSUE TITLE
Kode does not start on windows 10

### ISSUE THREAD

**Issue by 3ahptk** [TN-1/Kode#14]
After downloading and unzipping (v0.4.0); Kode will hang indefinitely on startup. I have been unable to run any of the previous versions of Kode as well.

**Comment by TN-1** [comment]
I develop on Windows 10 so it wont be something OS specific.  
Can you please try and launch Kode, Then have a look in the event viewer(Can be reached by using the search bar) for any errors under Application Logs(On the left hand side). If you can find anything relating to Kode screenshot would be helpful. Thanks :)

**Comment by 3ahptk** [comment]
Well, I am at a complete loss. For whatever reason my computer does not like the compiled executable of Kode. When I try searching for the event in the event viewer, it does not show up. Nor does it show up in the task manager nor the "top" script that I use in powershell. I cannot run the executable in debug mode in visual studio using the "attach process" because the process is never created. I also tried opening the executable as a solution and running in debug mode in visual studio, which had the effect of crashing my visual studio. However, when I downloaded, compiled, and ran the source code in visual studio it works fine (at least the first time I run it). Interestingly, the build will not rebuild because it says that the process Kode.exe is already running; to fix this I have to restart my computer.

This is probably unrelated but the TabControlEX.dll was missing the first time I started the visual studio soulution

UPDATE:
So tried finding/killing the process using:
`tasklist /svc /fi "imagename eq Kode.exe"`
`Taskkill /IM Kode.exe /T /F`
The process cannot be killed for some reason; it gives me:
`ERROR: The process "Kode.exe" with PID XXXX could not be terminated.`
`Reason: There is currently no instance executed by this task.`
I wonder if there might be a memory leak somewhere.

**Comment by TN-1** [comment]
You've got me perplexed, I haven't experienced any of the behaviour you are describing.
I assume you are using the code from the master branch rather than develop?
When you run the build through VS, What did you do before closing and how did you close?
The best thing I can think to do here is to just try and replicate what's happening on my end so I can see what's going on.

**Comment by 3ahptk** [comment]
I think I know what the problem was. I think that if there is a problem when the program crashes it will (for whatever reason) stay as a task for me. I wonder if some of my problems were from "stopping debugging" instead of closing the program using "quit". I still cant figure out why I cant use the compiled executable; ill just use the github code in debug mode from now on. Thanks again.

**Comment by TN-1** [comment]
I wish I could be of more help, Let me know if you manage to dig anything further up such as problems with the code that is causing it :)
