### ISSUE TITLE
Kode doesn't open files from file explorer (Win 10)

### ISSUE THREAD

**Issue by RobsterCraw** [TN-1/Kode#15]
I set Kode as the default prorgam for .ks files in Windows 10.  However, when I double click on a .ks file in my file explorer, Kode starts, but does not open the file that I clicked on.

**Comment by TN-1** [comment]
Id assume this is because I dont have any handling for arguments at startup which is mainly an oversight on my end and would have needed to be fixed before the next release. Thanks for letting me know!
