### ISSUE TITLE
Crash On First Launch [0.31]

### ISSUE THREAD

**Issue by odiefrom** [TN-1/Kode#2]
I'm launching Kode for the first time ever.  A window opens up asking me to confirm my Steam install, as C:\Program Files (x86)\Steam...which is correct.  I click "Yes", the window disappears, and then Windows reports that Kode crashed.

The dump file generated provides little information, basically the only pertinent information is "Exception Code: 0xE0434352".

_What I think is happening_ is that when the window asks me if that is my Steam install, it's ASSUMING that my games are installed in that directory.  This is false, my games are stored in D:\Games\SteamApps\common.  Perhaps the code just needs to check for the existing KSP folder safely, and if it doesn't exist, prompt the user to pick an install location?

I'm going to hold off on proceeding with messing with the program more, so that I can be of assistance diagnosing and trying anything.

~Krystee

**Comment by TN-1** [comment]
This shouldn't cause a crash the way you are describing. At launch when it autodetects it simply writes that path to a variable but does not access it again until you try and use it(Open/Save, Etc) so it shouldn't crash on launch.
Try using the 0.3.0 release, Maybe something broke on the windows side of things when I fixed the bug on Linux.

**Comment by odiefrom** [comment]
Running the 0.3.0 build doesn't have this issue and I'm able to load straight to the editor.  Strange.

Thanks!

**Comment by TN-1** [comment]
Strange indeed. I will need to look into it further as it could break future builds.  
Just out of interest, Could you please get a fresh copy of the 0.3.1 exe, Run it(Let it crash) and then send it to me?

**Comment by odiefrom** [comment]
One of the files mostly contains personal identifying information of the applications on my computer, so I won't include that here, if you want me to email it to you, I can send it that way.  It doesn't seem too relevant though.

Attached are the other two files Windows generated at the crash.  It looks like the error is "System.IO.FileNotFoundException".

[Kode 0.3.1 Crash.zip](https://github.com/TN-1/Kode/files/125902/Kode.0.3.1.Crash.zip)

**Comment by TN-1** [comment]
No its ok, I got the error from that dump. Thanks!  
Its seems that the "System.IO.FileNotFoundException" came from one of the dlls being missing, Specifically, TabControlEX.dll. I suspect that is because you downloaded 0.3.1 which only contains the exe with the fixed bug, Intended to overwritten an existing install which already contains the dlls needed. When you downloaded the 0.3 release you got all the dlls needed.  
Easy fix, I will edit the 0.3.1 release to say "Dont use this"

**Comment by odiefrom** [comment]
My apologies, I feel so dumb!  I must've missed a note or something somewhere saying that pre-release versions just drag and drop in the new files.  Sorry for wasting your time hunting for a bug that doesn't exist!

**Comment by TN-1** [comment]
Don't be sorry! 'Stuff' happens as they say, and I would rather have false alarms then missed bugs.
Thankyou for taking the time to help me with this :)
