### ISSUE TITLE
Feature Request - Keyboard shortcut to cycle through tabs

### ISSUE THREAD

**Issue by RobsterCraw** [TN-1/Kode#21]
I've found myself clicking on tabs back and forth a lot.  I think I already requested a feature for moving tabs to additional windows, but likewise, a keyboard shortcut for cycling through open tabs would be really handy.

**Comment by TN-1** [comment]
Tabs to other Windows will definitely not be included in 0.5, Maybe in 0.6. Keyboard shortcuts will be easy enough to include though.

**Comment by TN-1** [comment]
Behaviour i've implemented is CTRL+TAB will go forwards one, CTRL+SHIFT+TAB will go back one and CTRL+(1-9) will skip to that numbered tab.
