### ISSUE TITLE
Save error [0.3] [windows]

### ISSUE THREAD

**Issue by PhilTaken** [TN-1/Kode#3]
If you try to save an empty file directly after starting Kode there is an exception which says that parameter 'path' must not be zero.

**Comment by TN-1** [comment]
Thanks for the report, This is easy enough to fix.  
When you open a new tab or start Kode, You need to Open or Save As before you can save. I will correct it so that if you Save it will invoke a Save As instead.

**Comment by Gaiiden** [comment]
even when you use Save As, the tab title doesn't update with the name you've just saved it as

**Comment by TN-1** [comment]
@Gaiiden, Can you give me a little more info on what's happening? I just Saved As and the tab title updated as expected.

**Comment by Gaiiden** [comment]
can't get it to update for me, on W7 x64 - if I run the program, immediately go File->Save As and type in a name and press enter the tab still says untitled

**Comment by TN-1** [comment]
Interesting. I will look into it further.
