### ISSUE TITLE
saves don't save

### ISSUE THREAD

**Issue by Gaiiden** [TN-1/Kode#8]
I haven't found a way to reproduce this yet but just a heads up that I've noticed the \* going away when saving a file but the file's timestamp doesn't get updated looking at it in Explorer and opening it up in another program shows the latest updates weren't applied.

**Comment by TN-1** [comment]
This is odd indeed, I can't say I have seen this behaviour at all. If you could work out the exact circumstances and can reproduce it reliably, please do let me know.
I cant see how it would happen either, If the star is being removed then it should save because they are both inside the same check.

**Comment by TN-1** [comment]
Has this happened anymore?

**Comment by Gaiiden** [comment]
yes, I did notice it happening once this past weekend while script editing but again could not think of anything that could have caused it or to try to replicate it

**Comment by RobsterCraw** [comment]
I've noticed this bug as well.  But for me, I've had no problem reproducing it, both in 0.4.0 and the 0.5.0 Beta.  Basically, if I save a new file (not rewriting and existing file) it saves just fine.  If I use "save as" it overwrites the old file, and that works fine, but if I only hit save, the "*" goes away, but if I close and reopen the file, my changes are lost.  That is what happens every time.

**Comment by TN-1** [comment]
Ok, I have replicated this bug. Seems that when you hit 'Save', it is saving... Just without the file extension so you have "Test.ks"(Original file) and then "Test"(The file created by the Save)  
I probably broke it when I reorganized the code, Derp.
